# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-14-04-x64-virtualbox-cd-1.0.2"

  config.vm.network "forwarded_port", guest: 22, host:2222, id: "ssh"
  config.vm.network "forwarded_port", guest: 2224, host: 2224
  # continuous delivery demo
  config.vm.network "forwarded_port", guest: 8000, host: 18000
  # continuous delivery demo 2
  config.vm.network "forwarded_port", guest: 8001, host: 18001
  # continuous delivery demo 3
  config.vm.network "forwarded_port", guest: 8002, host: 18002
  # jenkins
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  # nexus
  config.vm.network "forwarded_port", guest: 8081, host: 18081
  # docker registry
  config.vm.network "forwarded_port", guest: 443, host: 1443

  config.vm.synced_folder ".", "/opt/docker_volumes"

  config.vm.provider "virtualbox" do |v|
    v.name = "continuous"
    v.memory = 4096
    v.cpus = 2
  end

end
