# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "xenial-server-cloudimg-amd64-vagrant-cd"

  # by default vagrant binds port 22 only to 127.0.0.1
  # following allows binding to all interfaces
  config.vm.network "forwarded_port", guest: 22, host: 18022, id: "ssh"

  # continuous delivery demo
  config.vm.network "forwarded_port", guest: 8000, host: 18000
  # continuous delivery demo 2
  config.vm.network "forwarded_port", guest: 8001, host: 18001
  # continuous delivery demo 3
  config.vm.network "forwarded_port", guest: 8002, host: 18002
  config.vm.network "forwarded_port", guest: 2224, host: 18024
  # docker private registry
  config.vm.network "forwarded_port", guest:  443, host: 18043
  # jenkins
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  # nexus
  config.vm.network "forwarded_port", guest: 8081, host: 18081
  # sonar
  config.vm.network "forwarded_port", guest: 8081, host: 18082

  # share project directory (the directory with the Vagrantfile) to /opt/docker_volumes
  config.vm.synced_folder ".", "/opt/docker_volumes"

  config.vm.provider "virtualbox" do |v|
    v.name = "continuous"
    v.memory = 8192
    v.cpus = 4
  end

end
