# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-14-04-x64-virtualbox-cd"
  
  config.vm.provider "virtualbox" do |v|
    v.name = "continuous"
    v.memory = 4096
    v.cpus = 2
  end

end
